name: Deployment Workflow

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/azure-cli-action@v1

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: "Library-mangment-system"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./build 
