name: Deployment Workflow

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/azure-cli-action@v1

    - name: Deploy to Azure Wep App
      uses: azure/webapps-deploy@v2
      with:
        app-name:''
        publish-profile:''
        package:./build
          
